### ISSUE TITLE
Licensing of the documentation

### ISSUE THREAD

**Issue by mniinio** [OAI/Documentation#17]
According to the OpenAPI project charter, section 7.3 , the documentation, by default, should be released under Creative Commons Attribution 4.0 International License. https://www.openapis.org/participate/how-to-contribute/governance

**Comment by earth2marsh** [comment]
Suggest updating the [config](https://github.com/OAI/Documentation/blob/47b00b11c38cfe79c7a41739fc341592d191aac1/_config.yml) file to say `© 2020 OpenAPI Initiative.` 

Might be good to include the license info in the footer, too? Such as:
```<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.```

And possibly a link to the github project, too, in order to encourage contributions or adaptations?

**Comment by mniinio** [comment]
Noticed that webron had already added the LICENSE doc in the repo in August, so I was planning to refer to that.
