### ISSUE TITLE
requestBodies are content/messagebodies not parameters

### ISSUE THREAD

**Issue by darrelmiller** [OAI/Documentation#7]
We intentionally moved requestBodies out of the parameter array in V3 because viewing then as parameters is misleading.

https://github.com/OAI/Documentation/blob/xavi/specification/specification.md

**Comment by segfaultxavi** [comment]
Can I have more background on this?
requestBodies can be considered as parameters (or parameter-like), since they are part of the request and they alter the answer the server will return, no?
What is it, exactly, that was deemed misleading?
Is it the word "parameter"?

I was planning on explaining parameters and requestBodies in the same page since they serve a similar purpose in my mind.
Should I call them collectively "query arguments" instead?

**Comment by segfaultxavi** [comment]
I re-titled the page to "Parameters and Payload of an Operation", and I've clearly separated them in the page:
https://github.com/OAI/Documentation/blob/master/specification-parameters.md

Is it better now?
